### ISSUE TITLE
Weights.lua:431: attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [SLOKnightfall/CovenantForge#10]
Updated to v1.3.3 and when I click on the Weights tab, I get the following error. Thanks,

3x CovenantForge\Modules\Weights.lua:431: attempt to index field '?' (a nil value)
[string "@CovenantForge\Modules\Weights.lua"]:431: in function `UpdateWeightList'
[string "@CovenantForge\CovenantForge-V1.3.3.lua"]:416: in function `CovenantForgeSavedTab_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
self = <table> {
 GetConduitWeight = <function> defined @CovenantForge\Modules\Weights.lua:122
 SetDefaultModuleLibraries = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 EnableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 baseName = "CovenantForge"
 IterateEmbeds = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 SecureHookScript = <function> defined @CovenantForge\Libs\AceHook-3.0\AceHook-3.0.lua:410
 RawHookScript = <function> defined @CovenantForge\Libs\AceHook-3.0\AceHook-3.0.lua:395
 Printf = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 CovForge_WeightTotalFrame = CovForge_WeightTotal {
 }
 defaultModuleState = true
 IsEnabled = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 Frame = <table> {
 }
 DisableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 scrollcontainer = <table> {
 }
 RegisterMessage = <function> defined @AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 Update = <function> defined @CovenantForge\CovenantForge.lua:597
 hooks = <table> {
 }
 db = <table> {
 }
 Soulbinds = <table> {
 }
 SetEnabledState = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @CovenantForge\Libs\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 RegisterEvent = <function> defined @AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 ClosePopups = <function> defined @CovenantForge\Modules\SavedPaths.lua:238
 IterateModules = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 RawHook = <function> defined @CovenantForge\Libs\AceHook-3.0\AceHook-3.0.lua:313
 StopNodeFX = <function> defined @CovenantForge\CovenantForge.lua:810
 conduitList = <table> {
 }
 ShowPopup = <function> defined @CovenantForge\Modules\SavedPaths.lua:226
 OnInitialize = <function> defined @CovenantForge\CovenantForge.lua:169
 NewModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 PathStorageFrame = CovForge_PathStorage {
 }
 defaultModuleLibraries = <table> {
 }
 optionsFrame = <unnamed> {
 }
 OpenOptionsMenu = <function> defined @CovenantForge\CovenantForge.lua:853
 UnregisterChatCommand = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:111
 viewed_spec = 251
 powers = <table> {
 }
 UpdateConduitList = <function> defined @CovenantForge\CovenantForge.lua:423
 weightdb = <table> {
 }
 Weights = <table> {
 }
 GetName = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 SecureHook = <function> defined @CovenantForge\Libs\AceHook-3.0\AceHook-3.0.lua:336
 Conduits = <table> {
 }
 SavePath = <function> defined @CovenantForge\Modules\SavedPaths.lua:121
 name = "CovenantForge"
 UpdateWeightList = <function> defined @CovenantForge\Modules\Weights.lua:317
 GetWeightPercent = <function> defined @CovenantForge\Modules\Weights.lua:255
 orderedModules = <table> {
 }
 GetSoulbindWeight = <function> defined @CovenantForge\Modules\Weights.lua:167
 Disable = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 GetTalentWeight = <function> defined @CovenantForge\Modules\Weights.lua:

**Comment by SLOKnightfall** [comment]
Fixed in the next update.
