### ISSUE TITLE
New Character - Weights.lua:51: attempt to index local 'covenantData' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [SLOKnightfall/CovenantForge#11]
Minor issue. Just started leveling a new character through Shadowlands. As soon as I logged in I got the following error. I'm assuming it's because they haven't chosen a covenant yet, but wanted to let you know in case you wanted to fix what ever bug is causing this for the future. Thanks.

1x CovenantForge\Modules\Weights.lua:51: attempt to index local 'covenantData' (a nil value)
[string "@CovenantForge\Modules\Weights.lua"]:51: in function <CovenantForge\Modules\Weights.lua:49>
[string "@CovenantForge\Modules\Weights.lua"]:83: in function `BuildWeightData'
[string "@CovenantForge\CovenantForge-V1.4.lua"]:221: in function <CovenantForge\CovenantForge.lua:220>
[string "=[C]"]: ?
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@PetTracker\addons\main\main.lua"]:46: in function `?'
[string "@PetTracker\libs\WildAddon-1.0\WildAddon-1.0-1.lua"]:20: in function <...dOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
[string "@PetTracker\libs\WildAddon-1.0\WildAddon-1.0-1.lua"]:56: in function <...dOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:504: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:551: in function `CombatLog_LoadUI'
[string "@FrameXML\UIParent.lua"]:1386: in function <FrameXML\UIParent.lua:1269>
[string "=[C]"]: ?

**Comment by SLOKnightfall** [comment]
Thanks. I'll get a fix out shortly.
