### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by BloodDragon2580** [SLOKnightfall/CovenantForge#7]
1x CovenantForge\CovenantForge-V1.1.1.lua:356: attempt to index field '?' (a nil value)
[string "@CovenantForge\CovenantForge-V1.1.1.lua"]:356: in function `BuildWeightData'
[string "@CovenantForge\CovenantForge-V1.1.1.lua"]:157: in function <CovenantForge\CovenantForge.lua:156>
[string "=[C]"]: ?
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by SLOKnightfall** [comment]
Should be fixed in V1.1.2
