### ISSUE TITLE
393: attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [SLOKnightfall/CovenantForge#8]
Just opened access to my Soulbinding forge and received the following error when I activated it. Thanks.

1x CovenantForge\CovenantForge-V1.1.lua:393: attempt to index field '?' (a nil value)
[string "@CovenantForge\CovenantForge-V1.1.lua"]:393: in function `GetTalentWeight'
[string "@CovenantForge\CovenantForge-V1.1.lua"]:445: in function `GetSoulbindWeight'
[string "@CovenantForge\CovenantForge-V1.1.lua"]:241: in function `Update'
[string "@CovenantForge\CovenantForge-V1.1.lua"]:226: in function `CreateSoulbindFrames'
[string "@CovenantForge\CovenantForge-V1.1.lua"]:137: in function <CovenantForge\CovenantForge.lua:137>

Locals:
self = <table> {
 GetSoulbindWeight = <function> defined @CovenantForge\CovenantForge.lua:417
 SetDefaultModuleLibraries = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:294
 UnregisterAllEvents = <function> defined @AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 GetWeightPercent = <function> defined @CovenantForge\CovenantForge.lua:511
 EnableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 RegisterChatCommand = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:85
 SecureHook = <function> defined @CovenantForge\Libs\AceHook-3.0\AceHook-3.0.lua:336
 defaultModuleLibraries = <table> {
 }
 optionsFrame = <unnamed> {
 }
 db = <table> {
 }
 UnregisterChatCommand = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:111
 RawHookScript = <function> defined @CovenantForge\Libs\AceHook-3.0\AceHook-3.0.lua:395
 baseName = "CovenantForge"
 UnhookAll = <function> defined @CovenantForge\Libs\AceHook-3.0\AceHook-3.0.lua:477
 Printf = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 Weights = <table> {
 }
 SetDefaultModulePrototype = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 Conduits = <table> {
 }
 CovForge_WeightTotalFrame = CovForge_WeightTotal {
 }
 GetTalentWeight = <function> defined @CovenantForge\CovenantForge.lua:390
 name = "CovenantForge"
 OnInitialize = <function> defined @CovenantForge\CovenantForge.lua:117
 IsEnabled = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 SetDefaultModuleState = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:387
 DisableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 Update = <function> defined @CovenantForge\CovenantForge.lua:231
 OnEnable = <function> defined @CovenantForge\CovenantForge.lua:156
 HookScript = <function> defined @CovenantForge\Libs\AceHook-3.0\AceHook-3.0.lua:366
 GetWeightData = <function> defined @CovenantForge\CovenantForge.lua:374
 RegisterMessage = <function> defined @AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Print = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:54
 SecureHookScript = <function> defined @CovenantForge\Libs\AceHook-3.0\AceHook-3.0.lua:410
 IsHooked = <function> defined @CovenantForge\Libs\AceHook-3.0\AceHook-3.0.lua:493
 Frame = <table> {
 }
 hooks = <table> {
 }
 IsModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:468
 BuildWeightData = <function> defined @CovenantForge\CovenantForge.lua:348
 SendMessage = <function> defined @AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 Soulbinds = <table> {
 }
 Unhook = <function> defined @CovenantForge\Libs\AceHook-3.0\AceHook-3.0.lua:418
 SetEnabledState = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @CovenantForge\Libs\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 Init = <table> {
 }
 RegisterEvent = <function> defined @AchieveIt\libs\CallbackHandler-1.0\C

**Comment by SLOKnightfall** [comment]
Should be fixed in V1.1.2
